# Generated by Django 3.2.8 on 2024-11-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_rename_description_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='direccion',
            field=models.TextField(null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
