# Generated by Django 4.2.25 on 2025-10-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_auto_20241123_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.TextField(blank=True, null=True, verbose_name='Fecha de Publicación'),
        ),
    ]
